Repository compsci-adl/courses-api, pull requests merged in 2024-11, with the labels that each got.

#46 chore: Switch to uv and ruff
  .github/workflows/lint.yml
  .gitignore
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  src/data_fetcher.py
  src/scraper.py
  src/server.py
  uv.lock
Labels: dependencies

#50 feat: Add Logging Functionality
  .env.example
  README.md
  src/data_fetcher.py
  src/data_parser.py
  src/log.py
  src/scraper.py
Labels: enhancement

#52 feat: Add Git Hook for Ruff
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  uv.lock
Labels: enhancement, dependencies
